[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Future of Hospitality: How Artificial Intelligence and Other Technologies Will Transform the Hospitality Industry"
